site_name: trajectoryGuide v1.0
site_author: Greydon Gilmore

# Repository
repo_name: GitHub
repo_url: https://github.com/greydongilmore/trajectoryGuide-site
edit_uri: https://github.com/greydongilmore/trajectoryGuide-site/blob/master/docs

# Copyright
copyright: Copyright &copy; 2021 Greydon Gilmore

# Configuration
dev_addr: 127.0.0.1:7000
use_directory_urls: false
theme:
  name: material
  custom_dir: material
  palette:
    scheme: 
    primary: red
    accent: red
  logo: img/trajectoryGuide.png
  favicon: img/trajectoryGuide_icon.svg

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: false

extra_css:
  - stylesheets/extra.css
  
# Plugins
plugins:
  - search

extra_javascript:
  - javascripts/config.js
  - https://unpkg.com/mermaid@8.4.4/dist/mermaid.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Installation: installation.md
  - Working in 3D Slicer:
    - User Interface: 3dslicer/01_interface.md
    - Saving Data: 3dslicer/02_saving_data.md
  - Modules:
    - Overview: widgets/00_overview.md
    - Patient Directory: widgets/01_patient_directory.md
    - Frame Detection: widgets/04_frame_detection.md
    - Registration: widgets/05_registration.md
    - Anatomical Fiducials: widgets/06_anatomical_fiducials.md
    - Preoperative Planning: widgets/07_preoperative_planning.md
    - Intraoperative Planning: widgets/08_intraoperative_planning.md
    - Postoperative Localization: widgets/09_postoperative_localization.md
    - Postoperative Programming: widgets/10_postoperative_programming.md
    - Data View: widgets/11_data_view.md
  - Product Manuals: manuals.md
  - About: about.md